[package]
name = "keycheck"
version = "0.1.0"
edition = "2021"

[dependencies]
ignore = "0.4.20"
regex = "1.5.4"
tempfile = "3.5.0"
rand = "0.8.5"
lazy_static = "1.4.0"
rayon = "1.7.0"

[dev-dependencies]
ethers = "2.0.3"
